### ISSUE TITLE
The Limit of Our Gaze appears in wrong order under FILMS

### ISSUE THREAD

**Issue by lauraturegano** [sonnetmedia/kjcc#21] opened 2015-09-21 23:42 UTC
When clicking on FILMS, The Limit of Our Gaze should be the first one since is October 2&3 and instead it shows  in third place

**Comment by budparr** [comment] 2015-09-21 23:43
That's a duplicate of the previous issue

**Comment by lauraturegano** [comment] 2015-09-21 23:45
You mean the double tag?
It's only tagged as "Film"

**Closed** 2015-09-22 03:48 UTC
